### ISSUE TITLE
NIF library not loaded. Trying to call method `_load`."

### ISSUE THREAD

**Issue by ijunaid8989** [eugenehp/elixir-motiondetection#1]
I cloned the repo and went on with the process but got that error

```
iex(2)> Motiondetection.test "test_images"
Doing compare_two_files with `7.jpg` and `4.jpg`
** (MatchError) no match of right hand side value: "NIF library not loaded. Trying to call method `_load`."
    (motiondetection) lib/motiondetection.ex:35: Motiondetection.compare_two_files/3
    (motiondetection) lib/motiondetection.ex:19: Motiondetection.recursively_list/3

```

**Comment by eugenehp** [comment]
@ijunaid8088 we had that issue last year, and if I remember probably something was wrong with the setup of the binary library (NIF library) that is being used.
